from app.ai.url_scrapper.scraper import WebScraper
from app.ai.pdf_parser.parser import PDFParser
from app.ai.cleaner.cleaner import TextCleaner
from app.ai.chunker.chunker import TextChunker
from app.ai.embeddings.embeddings import EmbeddingGenerator
from app.ai.metadata.metadata import MetadataGenerator
from app.ai.summarizer.summarizer import DocumentSummarizer


class AIPipeline:
    """
    AIPipeline

    Responsible for:
    - Orchestrating the complete AI pipeline
    - Processing URLs
    - Processing PDFs
    - Returning structured AI results

    This module coordinates all AI components but does not
    implement any AI logic itself.
    """

    def __init__(self):

        self.scraper = WebScraper()
        self.parser = PDFParser()
        self.cleaner = TextCleaner()
        self.chunker = TextChunker()
        self.embedder = EmbeddingGenerator()
        self.metadata = MetadataGenerator()
        self.summarizer = DocumentSummarizer()

    ###########################################################################
    # URL Processing
    ###########################################################################

    def process_url(
        self,
        url: str,
        resource_id: str,
    ) -> dict:
        """
        Process a webpage through the complete AI pipeline.

        Parameters
        ----------
        url
            URL to scrape.

        resource_id
            Resource ID generated by upload_service.py.
            Required so Retrieval Engine can associate vectors
            with this uploaded resource.

        Returns
        -------
        dict
            Complete AI pipeline result.
        """

        try:

            ###################################################################
            # Scrape webpage
            ###################################################################

            scraped = self.scraper.scrape(url)

            ###################################################################
            # Clean text
            ###################################################################

            cleaned_text = self.cleaner.clean(
                scraped["text"]
            )

            ###################################################################
            # Chunk text
            ###################################################################

            chunks = self.chunker.chunk(
                cleaned_text
            )

            ###################################################################
            # Generate embeddings
            ###################################################################

            embedded_chunks = self.embedder.generate(
                chunks
            )

            ###################################################################
            # Metadata
            ###################################################################

            metadata = self.metadata.generate(
                text=cleaned_text,
                title=scraped["title"],
                chunk_count=len(chunks),
            )

            # Required by Retrieval Engine
            metadata["resource_id"] = resource_id

            ###################################################################
            # Summary
            ###################################################################

            summary = self.summarizer.summarize(
                cleaned_text
            )

            ###################################################################
            # Build chunk structures
            ###################################################################

            chunk_data = []

            embedding_data = []

            for item in embedded_chunks:

                chunk_data.append(
                    {
                        "chunk_id": item["chunk_id"],
                        "text": item["text"],
                        "length": item["length"],
                    }
                )

                embedding_data.append(
                    {
                        "chunk_id": item["chunk_id"],
                        "embedding": item["embedding"],
                    }
                )

            ###################################################################
            # Final Output
            ###################################################################

            return {

                "resource_id": resource_id,

                "source_type": "url",

                "document": {

                    "url": scraped["url"],

                    "title": scraped["title"],

                    "author": scraped["author"],

                    "date": scraped["date"],

                    "filename": None,

                    "page_count": None,

                },

                "cleaned_text": cleaned_text,

                "chunks": chunk_data,

                "embeddings": embedding_data,

                "metadata": metadata,

                "summary": summary,

            }

        except Exception as e:

            raise RuntimeError(
                f"URL Processing Error: {e}"
            )

    ###########################################################################
    # PDF Processing
    ###########################################################################

    def process_pdf(
        self,
        pdf_path: str,
        resource_id: str,
    ) -> dict:
        """
        Process a PDF through the complete AI pipeline.

        Parameters
        ----------
        pdf_path
            Temporary PDF path.

        resource_id
            Resource ID generated by upload_service.py.

        Returns
        -------
        dict
            Complete AI pipeline result.
        """

        try:

            ###################################################################
            # Parse PDF
            ###################################################################

            parsed = self.parser.parse(
                pdf_path
            )

            ###################################################################
            # Clean text
            ###################################################################

            cleaned_text = self.cleaner.clean(
                parsed["text"]
            )

            ###################################################################
            # Chunk text
            ###################################################################

            chunks = self.chunker.chunk(
                cleaned_text
            )

            ###################################################################
            # Generate embeddings
            ###################################################################

            embedded_chunks = self.embedder.generate(
                chunks
            )

            ###################################################################
            # Metadata
            ###################################################################

            metadata = self.metadata.generate(
                text=cleaned_text,
                filename=parsed["filename"],
                chunk_count=len(chunks),
            )

            # Required by Retrieval Engine
            metadata["resource_id"] = resource_id

            ###################################################################
            # Summary
            ###################################################################

            summary = self.summarizer.summarize(
                cleaned_text
            )

            ###################################################################
            # Build chunk structures
            ###################################################################

            chunk_data = []

            embedding_data = []

            for item in embedded_chunks:

                chunk_data.append(
                    {
                        "chunk_id": item["chunk_id"],
                        "text": item["text"],
                        "length": item["length"],
                    }
                )

                embedding_data.append(
                    {
                        "chunk_id": item["chunk_id"],
                        "embedding": item["embedding"],
                    }
                )

            ###################################################################
            # Final Output
            ###################################################################

            return {

                "resource_id": resource_id,

                "source_type": "pdf",

                "document": {

                    "url": None,

                    "title": None,

                    "author": None,

                    "date": None,

                    "filename": parsed["filename"],

                    "page_count": parsed["page_count"],

                },

                "cleaned_text": cleaned_text,

                "chunks": chunk_data,

                "embeddings": embedding_data,

                "metadata": metadata,

                "summary": summary,

            }

        except Exception as e:

            raise RuntimeError(
                f"PDF Processing Error: {e}"
            )